using System.Diagnostics.CodeAnalysis;

namespace RedisDesktop.App;

/// <summary>
/// App-specific strings for all 13 UI languages. ARDM catalog keys stay in <see cref="UiCatalog"/>.
/// Order: en-US, zh-CN, zh-TW, tr-TR, ru-RU, pt-BR, de-DE, fr-FR, uk-UA, it-IT, es-ES, ko-KR, vi-VN.
/// </summary>
internal static class UiCatalogExtras
{
    private static readonly string[] Languages =
    [
        UiLanguages.EnUS, UiLanguages.ZhCN, UiLanguages.ZhTW, UiLanguages.TrTR, UiLanguages.RuRU,
        UiLanguages.PtBR, UiLanguages.DeDE, UiLanguages.FrFR, UiLanguages.UkUA, UiLanguages.ItIT,
        UiLanguages.EsES, UiLanguages.KoKR, UiLanguages.ViVN
    ];

    private static readonly Dictionary<string, string[]> Table = new(StringComparer.OrdinalIgnoreCase)
    {
        ["connect"] = R("Connect", "连接", "連線", "Bağlan", "Подключить", "Conectar", "Verbinden", "Connecter", "Підключити", "Connetti", "Conectar", "연결", "Kết nối"),
        ["disconnect"] = R("Disconnect", "断开", "斷線", "Kes", "Отключить", "Desconectar", "Trennen", "Déconnecter", "Від’єднати", "Disconnetti", "Desconectar", "연결 해제", "Ngắt kết nối"),
        ["pubsub"] = R("Pub/Sub", "Pub/Sub", "Pub/Sub", "Pub/Sub", "Pub/Sub", "Pub/Sub", "Pub/Sub", "Pub/Sub", "Pub/Sub", "Pub/Sub", "Pub/Sub", "Pub/Sub", "Pub/Sub"),
        ["benchmark"] = R("Benchmark", "压力测试", "壓力測試", "Yük testi", "Нагрузочный тест", "Teste de carga", "Lasttest", "Test de charge", "Навантажувальний тест", "Test di carico", "Prueba de carga", "부하 테스트", "Kiểm tra tải"),
        ["benchmark_hint"] = R(
            "Writes/reads test keys on a dedicated connection, not the browse session. First run should be PING with at most 1000 requests.",
            "会向服务器写入/读取测试 Key，使用独立连接，不占用当前浏览会话。第一次建议只跑 PING 且不超过 1000 次。",
            "會向伺服器寫入/讀取測試 Key，使用獨立連線，不占用目前瀏覽工作階段。第一次建議只跑 PING 且不超過 1000 次。",
            "Ayrı bir bağlantıda test anahtarları yazılır/okunur; tarama oturumu kullanılmaz. İlk çalıştırma en fazla 1000 PING olmalıdır.",
            "Пишет/читает тестовые ключи по отдельному подключению, не в сессии просмотра. Первый запуск — PING, не больше 1000 запросов.",
            "Grava/lê chaves de teste numa ligação dedicada, não na sessão de navegação. A primeira execução deve ser PING com no máximo 1000 pedidos.",
            "Schreibt/liest Test-Keys über eine eigene Verbindung, nicht die Browse-Sitzung. Beim ersten Lauf nur PING mit höchstens 1000 Anfragen.",
            "Écrit/lit des clés de test sur une connexion dédiée, pas la session de navigation. Premier essai : PING, 1000 requêtes max.",
            "Пише/читає тестові ключі окремим підключенням, не сесією перегляду. Перший запуск — PING, не більше 1000 запитів.",
            "Scrive/legge chiavi di test su una connessione dedicata, non la sessione di esplorazione. Prima esecuzione: PING, al massimo 1000 richieste.",
            "Escribe/lee claves de prueba en una conexión dedicada, no en la sesión de exploración. La primera ejecución debe ser PING con 1000 solicitudes como máximo.",
            "탐색 세션이 아닌 전용 연결에서 테스트 키를 읽고 씁니다. 첫 실행은 PING, 최대 1000회를 권장합니다.",
            "Ghi/đọc khóa thử trên kết nối riêng, không dùng phiên duyệt. Lần đầu nên chỉ PING tối đa 1000 yêu cầu."),
        ["benchmark_confirm"] = R(
            "This will send benchmark commands to Redis and may write keys prefixed with __rdbench:. Start?",
            "将向 Redis 发送压测命令，并可能写入前缀为 __rdbench: 的测试 Key。确定开始？",
            "將向 Redis 發送壓測命令，並可能寫入前綴為 __rdbench: 的測試 Key。確定開始？",
            "Redis’e yük testi komutları gönderilir ve __rdbench: önekli anahtarlar yazılabilir. Başlatılsın mı?",
            "На Redis будут отправлены команды теста и могут быть записаны ключи с префиксом __rdbench:. Начать?",
            "Isto enviará comandos de teste ao Redis e pode gravar chaves com prefixo __rdbench:. Iniciar?",
            "Es werden Lasttest-Befehle an Redis gesendet und Keys mit Präfix __rdbench: geschrieben. Starten?",
            "Des commandes de test seront envoyées à Redis et des clés __rdbench: pourront être écrites. Démarrer ?",
            "До Redis буде надіслано команди тесту, можуть з’явитися ключі з префіксом __rdbench:. Почати?",
            "Verranno inviati comandi di test a Redis e potrebbero essere scritte chiavi con prefisso __rdbench:. Avviare?",
            "Se enviarán comandos de prueba a Redis y pueden escribirse claves con prefijo __rdbench:. ¿Empezar?",
            "Redis에 부하 테스트 명령을 보내며 __rdbench: 접두사 키가 생길 수 있습니다. 시작할까요?",
            "Sẽ gửi lệnh kiểm tra tới Redis và có thể ghi khóa tiền tố __rdbench:. Bắt đầu?"),
        ["benchmark_cleanup"] = R("Delete test keys", "删除测试 Key", "刪除測試 Key", "Test anahtarlarını sil", "Удалить тестовые ключи", "Excluir chaves de teste", "Test-Keys löschen", "Supprimer les clés de test", "Видалити тестові ключі", "Elimina chiavi di test", "Eliminar claves de prueba", "테스트 키 삭제", "Xóa khóa thử"),
        ["benchmark_cleanup_confirm"] = R(
            "This will SCAN and delete test keys under this prefix. Continue?",
            "将 SCAN 并删除此前缀下的测试 Key。确定继续？",
            "將 SCAN 並刪除此前綴下的測試 Key。確定繼續？",
            "Bu önek altındaki test anahtarları SCAN edilip silinecek. Devam?",
            "Ключи с этим префиксом будут найдены SCAN и удалены. Продолжить?",
            "Isto fará SCAN e apagará as chaves de teste deste prefixo. Continuar?",
            "Test-Keys unter diesem Präfix werden per SCAN gelöscht. Fortfahren?",
            "SCAN puis suppression des clés de test de ce préfixe. Continuer ?",
            "SCAN і видалення тестових ключів з цим префіксом. Продовжити?",
            "SCAN ed eliminazione delle chiavi di test con questo prefisso. Continuare?",
            "Se hará SCAN y se eliminarán las claves de prueba de este prefijo. ¿Continuar?",
            "이 접두사의 테스트 키를 SCAN한 뒤 삭제합니다. 계속할까요?",
            "Sẽ SCAN và xóa khóa thử với tiền tố này. Tiếp tục?"),
        ["benchmark_requests"] = R("Requests", "请求数", "請求數", "İstek sayısı", "Запросы", "Requisições", "Anfragen", "Requêtes", "Запити", "Richieste", "Solicitudes", "요청 수", "Số yêu cầu"),
        ["benchmark_concurrency"] = R("Clients", "并发连接", "並行連線", "Eşzamanlı bağlantı", "Параллельные клиенты", "Clientes simultâneos", "Gleichzeitige Clients", "Clients simultanés", "Паралельні клієнти", "Client simultanei", "Clientes simultáneos", "동시 연결", "Kết nối đồng thời"),
        ["benchmark_pipeline"] = R("Pipeline", "Pipeline", "Pipeline", "Pipeline", "Pipeline", "Pipeline", "Pipeline", "Pipeline", "Pipeline", "Pipeline", "Pipeline", "Pipeline", "Pipeline"),
        ["benchmark_value_size"] = R("Value bytes", "Value 字节", "Value 位元組", "Değer baytı", "Размер значения", "Bytes do valor", "Wert in Bytes", "Octets de valeur", "Байти значення", "Byte del valore", "Bytes del valor", "값 바이트", "Byte giá trị"),
        ["benchmark_duration_mode"] = R("Run for duration", "按时长运行", "依時長執行", "Süreye göre çalıştır", "Запускать по времени", "Executar por duração", "Nach Dauer ausführen", "Exécuter pendant une durée", "За тривалістю", "Esegui per durata", "Ejecutar por duración", "시간 기준으로 실행", "Chạy theo thời lượng"),
        ["benchmark_qps"] = R("Live QPS", "实时 QPS", "即時 QPS", "Anlık QPS", "Текущий QPS", "QPS ao vivo", "Live-QPS", "QPS en direct", "Поточний QPS", "QPS in tempo reale", "QPS en vivo", "실시간 QPS", "QPS trực tiếp"),
        ["benchmark_latency"] = R("Latency (ms)", "延迟分布 (ms)", "延遲分布 (ms)", "Gecikme (ms)", "Задержка (мс)", "Latência (ms)", "Latenz (ms)", "Latence (ms)", "Затримка (мс)", "Latenza (ms)", "Latencia (ms)", "지연 (ms)", "Độ trễ (ms)"),
        ["benchmark_idle"] = R("Idle", "未开始", "未開始", "Boşta", "Не запущено", "Inativo", "Leerlauf", "Inactif", "Не запущено", "Inattivo", "Inactivo", "대기", "Chưa chạy"),
        ["benchmark_running"] = R("Benchmark running", "压测进行中", "壓測進行中", "Yük testi çalışıyor", "Тест выполняется", "Teste em execução", "Lasttest läuft", "Test en cours", "Тест виконується", "Test in corso", "Prueba en curso", "부하 테스트 진행 중", "Đang kiểm tra tải"),
        ["benchmark_cancelled"] = R("Cancelled", "已取消", "已取消", "İptal edildi", "Отменено", "Cancelado", "Abgebrochen", "Annulé", "Скасовано", "Annullato", "Cancelado", "취소됨", "Đã hủy"),
        ["benchmark_cluster_hint"] = R(
            "Cluster hashes test keys across slots. Keys use a dedicated prefix.",
            "Cluster 会按 Key 槽位散列到各节点；测试 Key 使用独立前缀。",
            "Cluster 會依 Key 槽位散列到各節點；測試 Key 使用獨立前綴。",
            "Cluster test anahtarlarını slotlara dağıtır. Anahtarlar ayrı bir önek kullanır.",
            "В кластере тестовые ключи хешируются по слотам. Используется отдельный префикс.",
            "O cluster distribui as chaves de teste pelos slots. Elas usam um prefixo próprio.",
            "Cluster verteilt Test-Keys über Slots. Keys nutzen ein eigenes Präfix.",
            "Le cluster répartit les clés de test entre les slots. Préfixe dédié.",
            "Кластер хешує тестові ключі за слотами. Використовується окремий префікс.",
            "Il cluster distribuisce le chiavi di test tra gli slot. Prefisso dedicato.",
            "El clúster reparte las claves de prueba entre slots. Usan un prefijo propio.",
            "클러스터는 테스트 키를 슬롯에 해시합니다. 전용 접두사를 사용합니다.",
            "Cluster băm khóa thử theo slot. Khóa dùng tiền tố riêng."),
        ["benchmark_opening"] = R("Opening benchmark connections…", "正在建立压测连接…", "正在建立壓測連線…", "Yük testi bağlantıları açılıyor…", "Открытие соединений теста…", "A abrir ligações de teste…", "Lasttest-Verbindungen werden geöffnet…", "Ouverture des connexions de test…", "Відкриття з’єднань тесту…", "Apertura connessioni di test…", "Abriendo conexiones de prueba…", "부하 테스트 연결을 여는 중…", "Đang mở kết nối kiểm tra…"),
        ["benchmark_fail"] = R("Benchmark failed: {0}", "压测失败：{0}", "壓測失敗：{0}", "Yük testi başarısız: {0}", "Тест не удался: {0}", "Falha no teste: {0}", "Lasttest fehlgeschlagen: {0}", "Échec du test : {0}", "Тест не вдався: {0}", "Test non riuscito: {0}", "Error en la prueba: {0}", "부하 테스트 실패: {0}", "Kiểm tra tải thất bại: {0}"),
        ["benchmark_cleaning"] = R("Deleting benchmark keys…", "正在删除测试 Key…", "正在刪除測試 Key…", "Test anahtarları siliniyor…", "Удаление тестовых ключей…", "A eliminar chaves de teste…", "Test-Keys werden gelöscht…", "Suppression des clés de test…", "Видалення тестових ключів…", "Eliminazione chiavi di test…", "Eliminando claves de prueba…", "테스트 키 삭제 중…", "Đang xóa khóa thử…"),
        ["benchmark_deleted"] = R("Deleted {0} benchmark keys", "已删除 {0} 个测试 Key", "已刪除 {0} 個測試 Key", "{0} test anahtarı silindi", "Удалено тестовых ключей: {0}", "Eliminadas {0} chaves de teste", "{0} Test-Keys gelöscht", "{0} clés de test supprimées", "Видалено тестових ключів: {0}", "Eliminate {0} chiavi di test", "Se eliminaron {0} claves de prueba", "테스트 키 {0}개 삭제됨", "Đã xóa {0} khóa thử"),
        ["benchmark_cleanup_fail"] = R("Cleanup failed: {0}", "清理失败：{0}", "清理失敗：{0}", "Temizlik başarısız: {0}", "Очистка не удалась: {0}", "Falha na limpeza: {0}", "Bereinigung fehlgeschlagen: {0}", "Échec du nettoyage : {0}", "Очищення не вдалося: {0}", "Pulizia non riuscita: {0}", "Error al limpiar: {0}", "정리 실패: {0}", "Dọn dẹp thất bại: {0}"),
        ["benchmark_warn_requests"] = R("This will send {0} requests and may load Redis heavily. Continue?", "将发送 {0} 次请求，可能明显增加 Redis 负载。确定继续？", "將發送 {0} 次請求，可能明顯增加 Redis 負載。確定繼續？", "{0} istek gönderilecek ve Redis yükü artabilir. Devam?", "Будет отправлено {0} запросов, нагрузка на Redis может вырасти. Продолжить?", "Isto enviará {0} pedidos e pode sobrecarregar o Redis. Continuar?", "Es werden {0} Anfragen gesendet und Redis stark belastet. Fortfahren?", "{0} requêtes seront envoyées et Redis peut être fortement chargé. Continuer ?", "Буде надіслано {0} запитів, Redis може бути сильно навантажено. Продовжити?", "Verranno inviate {0} richieste e Redis potrebbe essere sotto carico. Continuare?", "Se enviarán {0} solicitudes y Redis puede cargar mucho. ¿Continuar?", "{0}개 요청을 보내 Redis 부하가 커질 수 있습니다. 계속할까요?", "Sẽ gửi {0} yêu cầu và có thể làm Redis quá tải. Tiếp tục?"),
        ["benchmark_warn_duration"] = R("This will run for {0} seconds. Continue?", "将持续压测 {0} 秒。确定继续？", "將持續壓測 {0} 秒。確定繼續？", "Yük testi {0} saniye sürecek. Devam?", "Тест будет идти {0} с. Продолжить?", "Isto corre durante {0} segundos. Continuar?", "Der Test läuft {0} Sekunden. Fortfahren?", "Le test durera {0} secondes. Continuer ?", "Тест триватиме {0} с. Продовжити?", "Il test durerà {0} secondi. Continuare?", "La prueba durará {0} segundos. ¿Continuar?", "{0}초 동안 실행됩니다. 계속할까요?", "Sẽ chạy trong {0} giây. Tiếp tục?"),
        ["benchmark_progress"] = R("Done {0}    Fail {1}    {2}s", "完成 {0}    失败 {1}    {2}s", "完成 {0}    失敗 {1}    {2}s", "Bitti {0}    Hata {1}    {2}s", "Готово {0}    Ошибки {1}    {2}с", "Concluído {0}    Falhas {1}    {2}s", "Fertig {0}    Fehler {1}    {2}s", "Terminé {0}    Échecs {1}    {2}s", "Готово {0}    Помилки {1}    {2}с", "Completate {0}    Errori {1}    {2}s", "Hecho {0}    Fallos {1}    {2}s", "완료 {0}    실패 {1}    {2}s", "Xong {0}    Lỗi {1}    {2}s"),
        ["benchmark_summary_live"] = R("QPS {0}    p99 {1} ms", "QPS {0}    p99 {1} ms", "QPS {0}    p99 {1} ms", "QPS {0}    p99 {1} ms", "QPS {0}    p99 {1} мс", "QPS {0}    p99 {1} ms", "QPS {0}    p99 {1} ms", "QPS {0}    p99 {1} ms", "QPS {0}    p99 {1} мс", "QPS {0}    p99 {1} ms", "QPS {0}    p99 {1} ms", "QPS {0}    p99 {1} ms", "QPS {0}    p99 {1} ms"),
        ["benchmark_summary_done"] = R(
            "Done {0}/{1}    QPS {2}    {3}    p50 {4} / p95 {5} / p99 {6} / max {7} ms",
            "完成 {0}/{1}    QPS {2}    吞吐 {3}    p50 {4} / p95 {5} / p99 {6} / max {7} ms",
            "完成 {0}/{1}    QPS {2}    吞吐 {3}    p50 {4} / p95 {5} / p99 {6} / max {7} ms",
            "Bitti {0}/{1}    QPS {2}    {3}    p50 {4} / p95 {5} / p99 {6} / max {7} ms",
            "Готово {0}/{1}    QPS {2}    {3}    p50 {4} / p95 {5} / p99 {6} / max {7} мс",
            "Concluído {0}/{1}    QPS {2}    {3}    p50 {4} / p95 {5} / p99 {6} / max {7} ms",
            "Fertig {0}/{1}    QPS {2}    {3}    p50 {4} / p95 {5} / p99 {6} / max {7} ms",
            "Terminé {0}/{1}    QPS {2}    {3}    p50 {4} / p95 {5} / p99 {6} / max {7} ms",
            "Готово {0}/{1}    QPS {2}    {3}    p50 {4} / p95 {5} / p99 {6} / max {7} мс",
            "Completate {0}/{1}    QPS {2}    {3}    p50 {4} / p95 {5} / p99 {6} / max {7} ms",
            "Hecho {0}/{1}    QPS {2}    {3}    p50 {4} / p95 {5} / p99 {6} / max {7} ms",
            "완료 {0}/{1}    QPS {2}    {3}    p50 {4} / p95 {5} / p99 {6} / max {7} ms",
            "Xong {0}/{1}    QPS {2}    {3}    p50 {4} / p95 {5} / p99 {6} / max {7} ms"),
        ["stop"] = R("Stop", "停止", "停止", "Durdur", "Стоп", "Parar", "Stopp", "Arrêter", "Стоп", "Ferma", "Detener", "중지", "Dừng"),
        ["seconds"] = R("sec", "秒", "秒", "sn", "с", "s", "s", "s", "с", "s", "s", "초", "giây"),
        ["no_slow_log"] = R("No Slow Log", "没有慢日志", "沒有慢日誌", "Yavaş günlük yok", "Нет медленных запросов", "Sem Slow Log", "Kein Slow Log", "Pas de Slow Log", "Немає повільних запитів", "Nessun Slow Log", "Sin Slow Log", "슬로 로그 없음", "Không có Slow Log"),
        ["slow_log_hint"] = R(
            "Via SLOWLOG GET. Threshold: CONFIG GET slowlog-log-slower-than. Length: CONFIG GET slowlog-max-len. Unit: μs, 1000μs = 1ms.",
            "通过 SLOWLOG GET，阈值：CONFIG GET slowlog-log-slower-than，条数：CONFIG GET slowlog-max-len。单位 μs，1000μs = 1ms。",
            "透過 SLOWLOG GET，閾值：CONFIG GET slowlog-log-slower-than，條數：CONFIG GET slowlog-max-len。單位 μs，1000μs = 1ms。",
            "SLOWLOG GET ile. Eşik: CONFIG GET slowlog-log-slower-than. Uzunluk: CONFIG GET slowlog-max-len. Birim μs, 1000μs = 1ms.",
            "Через SLOWLOG GET. Порог: CONFIG GET slowlog-log-slower-than. Длина: CONFIG GET slowlog-max-len. Единица μs, 1000μs = 1ms.",
            "Via SLOWLOG GET. Limiar: CONFIG GET slowlog-log-slower-than. Tamanho: CONFIG GET slowlog-max-len. Unidade μs, 1000μs = 1ms.",
            "Über SLOWLOG GET. Schwelle: CONFIG GET slowlog-log-slower-than. Länge: CONFIG GET slowlog-max-len. Einheit μs, 1000μs = 1ms.",
            "Via SLOWLOG GET. Seuil : CONFIG GET slowlog-log-slower-than. Longueur : CONFIG GET slowlog-max-len. Unité μs, 1000μs = 1ms.",
            "Через SLOWLOG GET. Поріг: CONFIG GET slowlog-log-slower-than. Довжина: CONFIG GET slowlog-max-len. Одиниця μs, 1000μs = 1ms.",
            "Tramite SLOWLOG GET. Soglia: CONFIG GET slowlog-log-slower-than. Lunghezza: CONFIG GET slowlog-max-len. Unità μs, 1000μs = 1ms.",
            "Vía SLOWLOG GET. Umbral: CONFIG GET slowlog-log-slower-than. Longitud: CONFIG GET slowlog-max-len. Unidad μs, 1000μs = 1ms.",
            "SLOWLOG GET 사용. 임계값: CONFIG GET slowlog-log-slower-than. 길이: CONFIG GET slowlog-max-len. 단위 μs, 1000μs = 1ms.",
            "Qua SLOWLOG GET. Ngưỡng: CONFIG GET slowlog-log-slower-than. Độ dài: CONFIG GET slowlog-max-len. Đơn vị μs, 1000μs = 1ms."),
        ["slow_log_time"] = R("Time", "时间", "時間", "Zaman", "Время", "Hora", "Zeit", "Heure", "Час", "Ora", "Hora", "시간", "Thời gian"),
        ["slow_log_source"] = R("Source", "来源", "來源", "Kaynak", "Источник", "Origem", "Quelle", "Source", "Джерело", "Origine", "Origen", "출처", "Nguồn"),
        ["cost"] = R("Cost", "耗时", "耗時", "Süre", "Затраты", "Custo", "Dauer", "Coût", "Витрати", "Costo", "Coste", "소요", "Chi phí"),
        ["command"] = R("Command", "命令", "命令", "Komut", "Команда", "Comando", "Befehl", "Commande", "Команда", "Comando", "Comando", "명령", "Lệnh"),
        ["size"] = R("Size", "Size", "Size", "Boyut", "Размер", "Tamanho", "Größe", "Taille", "Розмір", "Dimensione", "Tamaño", "크기", "Kích thước"),
        ["min_size_kb"] = R("Min Size (KB)", "最小 Size (KB)", "最小 Size (KB)", "Min. boyut (KB)", "Мин. размер (КБ)", "Tamanho mín. (KB)", "Min. Größe (KB)", "Taille min. (Ko)", "Мін. розмір (КБ)", "Dimensione min. (KB)", "Tamaño mín. (KB)", "최소 크기 (KB)", "Size tối thiểu (KB)"),
        ["memory_analysis_hint"] = R(
            "This runs SCAN and MEMORY USAGE and may affect latency. Size 0 usually means MEMORY is disabled.",
            "会 SCAN 并调用 MEMORY USAGE，可能影响延迟。结果为 0 时 MEMORY 可能已被禁用。",
            "會 SCAN 並呼叫 MEMORY USAGE，可能影響延遲。結果為 0 時 MEMORY 可能已被停用。",
            "SCAN ve MEMORY USAGE çalışır, gecikmeyi etkileyebilir. Size 0 genelde MEMORY’nin kapalı olduğunu gösterir.",
            "Выполняются SCAN и MEMORY USAGE, возможна задержка. Size 0 обычно значит, что MEMORY отключён.",
            "Isto executa SCAN e MEMORY USAGE e pode afetar a latência. Size 0 costuma significar que MEMORY está desativado.",
            "Führt SCAN und MEMORY USAGE aus und kann die Latenz beeinflussen. Size 0 bedeutet oft, dass MEMORY deaktiviert ist.",
            "Exécute SCAN et MEMORY USAGE et peut affecter la latence. Size 0 signifie souvent que MEMORY est désactivé.",
            "Виконує SCAN і MEMORY USAGE, може вплинути на затримку. Size 0 зазвичай означає, що MEMORY вимкнено.",
            "Esegue SCAN e MEMORY USAGE e può influire sulla latenza. Size 0 di solito indica che MEMORY è disabilitato.",
            "Ejecuta SCAN y MEMORY USAGE y puede afectar la latencia. Size 0 suele indicar que MEMORY está deshabilitado.",
            "SCAN과 MEMORY USAGE를 실행하며 지연에 영향을 줄 수 있습니다. Size 0은 보통 MEMORY가 비활성임을 뜻합니다.",
            "Chạy SCAN và MEMORY USAGE, có thể ảnh hưởng độ trễ. Size 0 thường nghĩa là MEMORY đã tắt."),
        ["analyze_folder"] = R("Analyze This Prefix", "分析该前缀", "分析此前綴", "Bu öneki analiz et", "Анализ этого префикса", "Analisar este prefixo", "Dieses Präfix analysieren", "Analyser ce préfixe", "Аналіз цього префікса", "Analizza questo prefisso", "Analizar este prefijo", "이 접두사 분석", "Phân tích tiền tố này"),
        ["color_red"] = R("Red", "红", "紅", "Kırmızı", "Красный", "Vermelho", "Rot", "Rouge", "Червоний", "Rosso", "Rojo", "빨강", "Đỏ"),
        ["color_orange"] = R("Orange", "橙", "橙", "Turuncu", "Оранжевый", "Laranja", "Orange", "Orange", "Помаранчевий", "Arancione", "Naranja", "주황", "Cam"),
        ["color_green"] = R("Green", "绿", "綠", "Yeşil", "Зелёный", "Verde", "Grün", "Vert", "Зелений", "Verde", "Verde", "초록", "Xanh lục"),
        ["color_blue"] = R("Blue", "蓝", "藍", "Mavi", "Синий", "Azul", "Blau", "Bleu", "Синій", "Blu", "Azul", "파랑", "Xanh dương"),
        ["color_purple"] = R("Purple", "紫", "紫", "Mor", "Фиолетовый", "Roxo", "Lila", "Violet", "Фіолетовий", "Viola", "Morado", "보라", "Tím"),
        ["color_none"] = R("None", "无", "無", "Yok", "Нет", "Nenhum", "Keine", "Aucun", "Немає", "Nessuno", "Ninguno", "없음", "Không"),
        ["more"] = R("More", "更多", "更多", "Daha fazla", "Ещё", "Mais", "Mehr", "Plus", "Ще", "Altro", "Más", "더보기", "Thêm"),
        ["flushdb_type_y"] = R("Type y to confirm flushing the current database.", "请输入 y 以确认清空当前数据库。", "請輸入 y 以確認清空目前資料庫。", "Geçerli veritabanını temizlemek için y yazın.", "Введите y, чтобы подтвердить очистку текущей БД.", "Digite y para confirmar a limpeza da base atual.", "Geben Sie y ein, um die aktuelle DB zu leeren.", "Saisissez y pour confirmer le vidage de la base actuelle.", "Введіть y, щоб підтвердити очищення поточної БД.", "Digita y per confermare lo svuotamento del DB corrente.", "Escriba y para confirmar el vaciado de la base actual.", "현재 DB를 비우려면 y를 입력하세요.", "Nhập y để xác nhận xóa DB hiện tại."),
        ["clone"] = R("Clone", "克隆", "複製", "Kopyala", "Клонировать", "Clonar", "Duplizieren", "Cloner", "Клонувати", "Clona", "Clonar", "복제", "Nhân bản"),
        ["delete"] = R("Delete", "删除", "刪除", "Sil", "Удалить", "Excluir", "Löschen", "Supprimer", "Видалити", "Elimina", "Eliminar", "삭제", "Xóa"),
        ["move_to_group"] = R("Move to group", "移动到分组", "移至分組", "Gruba taşı", "Переместить в группу", "Mover para grupo", "In Gruppe verschieben", "Déplacer vers un groupe", "Перемістити до групи", "Sposta nel gruppo", "Mover a grupo", "그룹으로 이동", "Chuyển vào nhóm"),
        ["font_default"] = R("Default", "默认", "預設", "Varsayılan", "По умолчанию", "Padrão", "Standard", "Par défaut", "Типово", "Predefinito", "Predeterminado", "기본", "Mặc định"),
        ["font_picker_tip"] = R(
            "The list is every font installed on this computer. Each item is previewed in its own typeface. Your pick is followed by system fallbacks so other scripts still render. Choose Default to keep the built-in UI font.",
            "列表为本机已安装的全部字体。下拉项按该字体预览。选定后会自动拼接系统多语言回退字体，避免缺字。选「默认」则使用界面自带字体。",
            "列表為本機已安裝的全部字型。下拉項會以該字型預覽。選定後會自動拼接系統多語系後備字型，避免缺字。選「預設」則使用介面內建字型。",
            "Liste bu bilgisayardaki tüm yüklü yazı tipleridir. Her öğe kendi yazı tipinde önizlenir. Seçimden sonra diğer yazılar için sistem yedekleri eklenir. Varsayılan, yerleşik arayüz yazı tipidir.",
            "Список — все установленные шрифты. Каждый пункт показывается своим начертанием. После выбора добавляются системные запасные шрифты. «По умолчанию» — встроенный шрифт интерфейса.",
            "A lista inclui todas as fontes instaladas neste computador. Cada item é pré-visualizado no próprio tipo. A escolha é seguida de substitutos do sistema. Padrão usa a fonte da interface.",
            "Die Liste enthält alle auf diesem Computer installierten Schriftarten. Jeder Eintrag wird in der eigenen Schrift dargestellt. Danach folgen System-Fallbacks. Standard ist die UI-Schrift.",
            "La liste contient toutes les polices installées. Chaque élément est prévisualisé dans sa police. Des polices de repli système suivent. Par défaut conserve la police de l’interface.",
            "Список — усі встановлені шрифти. Кожен пункт показано власним накресленням. Після вибору додаються системні запасні шрифти. «Типово» — вбудований шрифт інтерфейсу.",
            "L’elenco include tutti i font installati. Ogni voce è in anteprima nel proprio carattere. Seguono i fallback di sistema. Predefinito mantiene il font dell’interfaccia.",
            "La lista incluye todas las fuentes instaladas. Cada elemento se previsualiza con su tipo. Después se añaden fuentes de respaldo del sistema. Predeterminado usa la fuente de la interfaz.",
            "이 컴퓨터에 설치된 모든 글꼴 목록입니다. 각 항목은 해당 글꼴로 미리 봅니다. 선택 후 다른 문자를 위한 시스템 대체 글꼴이 이어집니다. 기본은 내장 UI 글꼴입니다.",
            "Danh sách gồm mọi phông đã cài trên máy. Mỗi mục xem trước bằng đúng phông đó. Sau lựa chọn sẽ thêm phông dự phòng hệ thống. Mặc định dùng phông giao diện."),
        ["latest_version"] = R("Latest Version", "最新版本", "最新版本", "Son sürüm", "Последняя версия", "Última versão", "Neueste Version", "Dernière version", "Остання версія", "Ultima versione", "Última versión", "최신 버전", "Phiên bản mới nhất"),
        ["update_check_failed"] = R("Could not read the latest GitHub release.", "无法读取 GitHub 最新版本。", "無法讀取 GitHub 最新版本。", "GitHub’daki son sürüm okunamadı.", "Не удалось прочитать последний релиз GitHub.", "Não foi possível ler o último release do GitHub.", "Die neueste GitHub-Version konnte nicht gelesen werden.", "Impossible de lire la dernière version GitHub.", "Не вдалося прочитати останній реліз GitHub.", "Impossibile leggere l’ultima release GitHub.", "No se pudo leer la última versión de GitHub.", "GitHub 최신 버전을 읽지 못했습니다.", "Không đọc được bản phát hành GitHub mới nhất."),
        ["dont_remind"] = R("Don't remind", "不再提示", "不再提示", "Bir daha gösterme", "Больше не напоминать", "Não lembrar", "Nicht mehr erinnern", "Ne plus rappeler", "Більше не нагадувати", "Non ricordare", "No recordar", "다시 알리지 않음", "Không nhắc lại"),
        ["check_updates_on_startup"] = R("Check for updates at startup", "启动时检查更新", "啟動時檢查更新", "Başlangıçta güncellemeleri denetle", "Проверять обновления при запуске", "Verificar atualizações ao iniciar", "Beim Start nach Updates suchen", "Vérifier les mises à jour au démarrage", "Перевіряти оновлення під час запуску", "Controlla aggiornamenti all’avvio", "Buscar actualizaciones al iniciar", "시작 시 업데이트 확인", "Kiểm tra cập nhật khi khởi động"),
        ["clear_cache_done"] = R("Cache cleared", "已清除缓存", "已清除快取", "Önbellek temizlendi", "Кэш очищен", "Cache limpo", "Cache geleert", "Cache vidé", "Кеш очищено", "Cache svuotata", "Caché borrada", "캐시가 지워짐", "Đã xóa bộ nhớ đệm"),
        ["open_config_folder"] = R("Open Config Folder", "打开配置目录", "開啟設定目錄", "Yapılandırma klasörünü aç", "Открыть папку настроек", "Abrir pasta de configuração", "Konfigurationsordner öffnen", "Ouvrir le dossier de configuration", "Відкрити теку налаштувань", "Apri cartella di configurazione", "Abrir carpeta de configuración", "설정 폴더 열기", "Mở thư mục cấu hình"),
        ["hotkey_desc"] = R("Description", "说明", "說明", "Açıklama", "Описание", "Descrição", "Beschreibung", "Description", "Опис", "Descrizione", "Descripción", "설명", "Mô tả"),
        ["only_write"] = R("Only Write", "仅写命令", "僅寫命令", "Yalnızca yazma", "Только запись", "Somente escrita", "Nur Schreibbefehle", "Écriture uniquement", "Лише запис", "Solo scrittura", "Solo escritura", "쓰기만", "Chỉ lệnh ghi"),
        ["empty_workspace"] = R("Connect a Redis instance from the sidebar", "从左侧连接一个 Redis 实例", "從左側連線一個 Redis 執行個體", "Kenar çubuğundan bir Redis örneğine bağlanın", "Подключите Redis из боковой панели", "Ligue uma instância Redis na barra lateral", "Verbinden Sie eine Redis-Instanz in der Seitenleiste", "Connectez une instance Redis depuis la barre latérale", "Підключіть Redis з бічної панелі", "Connetti un’istanza Redis dalla barra laterale", "Conecte una instancia Redis desde la barra lateral", "사이드바에서 Redis 인스턴스를 연결하세요", "Kết nối Redis từ thanh bên"),
        ["empty_keys"] = R("No Data", "暂无数据", "暫無資料", "Veri yok", "Нет данных", "Sem dados", "Keine Daten", "Aucune donnée", "Немає даних", "Nessun dato", "Sin datos", "데이터 없음", "Không có dữ liệu"),
        ["home"] = R("Home", "首页", "首頁", "Ana sayfa", "Главная", "Início", "Startseite", "Accueil", "Головна", "Home", "Inicio", "홈", "Trang chủ"),
        ["empty_connections"] = R("No connections yet. Click New Connection above.", "还没有连接。点上方「新建连接」开始。", "還沒有連線。點上方「新建連線」開始。", "Henüz bağlantı yok. Yukarıdan Yeni Bağlantı’ya tıklayın.", "Подключений пока нет. Нажмите «Новое подключение» выше.", "Ainda não há ligações. Clique em Nova ligação acima.", "Noch keine Verbindungen. Klicken Sie oben auf Neue Verbindung.", "Pas encore de connexions. Cliquez sur Nouvelle connexion ci-dessus.", "Ще немає підключень. Натисніть «Нове підключення» вище.", "Nessuna connessione. Fai clic su Nuova connessione in alto.", "Aún no hay conexiones. Pulse Nueva conexión arriba.", "연결이 없습니다. 위의 새 연결을 누르세요.", "Chưa có kết nối. Bấm Kết nối mới ở trên."),
        ["pick_key"] = R("Select a key on the left", "在左侧选择一个 Key", "在左側選擇一個 Key", "Soldan bir anahtar seçin", "Выберите ключ слева", "Selecione uma chave à esquerda", "Wählen Sie links einen Key", "Sélectionnez une clé à gauche", "Виберіть ключ ліворуч", "Seleziona una chiave a sinistra", "Seleccione una clave a la izquierda", "왼쪽에서 키를 선택하세요", "Chọn một khóa ở bên trái"),
        ["database_alias"] = R("DB alias (optional)", "DB 别名（可空）", "DB 別名（可空）", "DB takma adı (isteğe bağlı)", "Псевдоним БД (необязательно)", "Alias da DB (opcional)", "DB-Alias (optional)", "Alias DB (facultatif)", "Псевдонім БД (необов’язково)", "Alias DB (facoltativo)", "Alias de DB (opcional)", "DB 별칭 (선택)", "Bí danh DB (tùy chọn)"),
        ["separator_placeholder"] = R("Empty To Disable Tree View", "留空则关闭树形视图", "留空則關閉樹狀檢視", "Boş bırakınca ağaç görünümü kapanır", "Пустое значение отключает дерево", "Vazio desativa a árvore", "Leer lässt die Baumansicht aus", "Vide désactive l’arborescence", "Порожнє вимикає дерево", "Vuoto disattiva la vista ad albero", "Vacío desactiva la vista de árbol", "비우면 트리 보기 해제", "Để trống sẽ tắt cây"),
        ["acl_username_hint"] = R("ACL in Redis >= 6.0", "Redis 6.0+ ACL", "Redis 6.0+ ACL", "Redis 6.0+ ACL", "ACL в Redis >= 6.0", "ACL no Redis >= 6.0", "ACL in Redis >= 6.0", "ACL Redis >= 6.0", "ACL у Redis >= 6.0", "ACL in Redis >= 6.0", "ACL en Redis >= 6.0", "Redis 6.0+ ACL", "ACL Redis >= 6.0"),
        ["skip_cert_validation"] = R("Skip certificate validation (insecure)", "跳过证书校验（不安全）", "略過憑證驗證（不安全）", "Sertifika doğrulamayı atla (güvensiz)", "Пропустить проверку сертификата (небезопасно)", "Ignorar validação do certificado (inseguro)", "Zertifikatsprüfung überspringen (unsicher)", "Ignorer la validation du certificat (non sécurisé)", "Пропустити перевірку сертифіката ( небезпечно)", "Salta convalida certificato (non sicuro)", "Omitir validación del certificado (inseguro)", "인증서 검사 건너뛰기 (안전하지 않음)", "Bỏ kiểm tra chứng chỉ (không an toàn)"),
        ["ok"] = R("OK", "确定", "確定", "Tamam", "ОК", "OK", "OK", "OK", "ОК", "OK", "Aceptar", "확인", "OK"),
        ["color_tag"] = R("Color tag", "颜色标记", "顏色標記", "Renk etiketi", "Цветовая метка", "Etiqueta de cor", "Farbmarkierung", "Étiquette de couleur", "Кольорова мітка", "Etichetta colore", "Etiqueta de color", "색 태그", "Nhãn màu"),
        ["show_password"] = R("Show passwords", "显示密码", "顯示密碼", "Parolaları göster", "Показать пароли", "Mostrar senhas", "Passwörter anzeigen", "Afficher les mots de passe", "Показати паролі", "Mostra password", "Mostrar contraseñas", "비밀번호 표시", "Hiện mật khẩu"),
        ["shortcuts"] = R("Ctrl+N New connection · Ctrl+, Settings · Ctrl+G Command log", "Ctrl+N 新建连接 · Ctrl+, 设置 · Ctrl+G 命令日志", "Ctrl+N 新建連線 · Ctrl+, 設定 · Ctrl+G 命令日誌", "Ctrl+N Yeni bağlantı · Ctrl+, Ayarlar · Ctrl+G Komut günlüğü", "Ctrl+N Новое подключение · Ctrl+, Настройки · Ctrl+G Журнал команд", "Ctrl+N Nova ligação · Ctrl+, Definições · Ctrl+G Registo de comandos", "Ctrl+N Neue Verbindung · Ctrl+, Einstellungen · Ctrl+G Befehlsprotokoll", "Ctrl+N Nouvelle connexion · Ctrl+, Paramètres · Ctrl+G Journal des commandes", "Ctrl+N Нове підключення · Ctrl+, Налаштування · Ctrl+G Журнал команд", "Ctrl+N Nuova connessione · Ctrl+, Impostazioni · Ctrl+G Registro comandi", "Ctrl+N Nueva conexión · Ctrl+, Ajustes · Ctrl+G Registro de comandos", "Ctrl+N 새 연결 · Ctrl+, 설정 · Ctrl+G 명령 로그", "Ctrl+N Kết nối mới · Ctrl+, Cài đặt · Ctrl+G Nhật ký lệnh"),
        ["hotkey_close_tab"] = R("Close Tab", "关闭 Tab", "關閉分頁", "Sekmeyi kapat", "Закрыть вкладку", "Fechar separador", "Tab schließen", "Fermer l’onglet", "Закрити вкладку", "Chiudi scheda", "Cerrar pestaña", "탭 닫기", "Đóng tab"),
        ["hotkey_refresh_tab"] = R("Refresh [Status / Key / Slow Log / Memory]", "刷新 [Status / Key / Slow Log / 内存分析]", "重新整理 [Status / Key / Slow Log / 記憶體分析]", "Yenile [Status / Key / Slow Log / Bellek]", "Обновить [Status / Key / Slow Log / Память]", "Atualizar [Status / Key / Slow Log / Memória]", "Aktualisieren [Status / Key / Slow Log / Speicher]", "Actualiser [Status / Key / Slow Log / Mémoire]", "Оновити [Status / Key / Slow Log / Пам’ять]", "Aggiorna [Status / Key / Slow Log / Memoria]", "Actualizar [Status / Key / Slow Log / Memoria]", "새로고침 [Status / Key / Slow Log / 메모리]", "Làm mới [Status / Key / Slow Log / Bộ nhớ]"),
        ["hotkey_delete_key"] = R("Delete key [Key Tab]", "删除 Key [Key Tab]", "刪除 Key [Key 分頁]", "Anahtarı sil [Key sekmesi]", "Удалить ключ [вкладка Key]", "Excluir chave [separador Key]", "Key löschen [Key-Tab]", "Supprimer la clé [onglet Key]", "Видалити ключ [вкладка Key]", "Elimina chiave [scheda Key]", "Eliminar clave [pestaña Key]", "키 삭제 [Key 탭]", "Xóa khóa [tab Key]"),
        ["hotkey_save_key"] = R("Save [Key Tab]", "保存 [Key Tab]", "儲存 [Key 分頁]", "Kaydet [Key sekmesi]", "Сохранить [вкладка Key]", "Guardar [separador Key]", "Speichern [Key-Tab]", "Enregistrer [onglet Key]", "Зберегти [вкладка Key]", "Salva [scheda Key]", "Guardar [pestaña Key]", "저장 [Key 탭]", "Lưu [tab Key]"),
        ["hotkey_clear_cli"] = R("Clear [CLI Tab]", "清屏 [CLI Tab]", "清屏 [CLI 分頁]", "Temizle [CLI sekmesi]", "Очистить [вкладка CLI]", "Limpar [separador CLI]", "Leeren [CLI-Tab]", "Effacer [onglet CLI]", "Очистити [вкладка CLI]", "Pulisci [scheda CLI]", "Limpiar [pestaña CLI]", "지우기 [CLI 탭]", "Xóa màn hình [tab CLI]"),
        ["hotkey_open_new_tab"] = R("Open key in a new tab", "在新 Tab 打开 Key", "在新分頁開啟 Key", "Anahtarı yeni sekmede aç", "Открыть ключ в новой вкладке", "Abrir chave num novo separador", "Key in neuem Tab öffnen", "Ouvrir la clé dans un nouvel onglet", "Відкрити ключ у новій вкладці", "Apri chiave in una nuova scheda", "Abrir clave en una pestaña nueva", "새 탭에서 키 열기", "Mở khóa trong tab mới"),
        ["hotkey_tips"] = R("Hotkey tips", "快捷键说明", "快速鍵說明", "Kısayol ipuçları", "Подсказки по горячим клавишам", "Dicas de atalhos", "Tastenkürzel", "Raccourcis", "Підказки гарячих клавіш", "Suggerimenti tasti", "Atajos", "단축키 안내", "Phím tắt"),
        ["export_warning"] = R(
            "Export includes machine-encrypted secrets. Passwords will not decrypt on another PC.",
            "导出会包含本机加密后的密码密文，换电脑后密码无法解密，需要重新填写。",
            "匯出會包含本機加密後的密碼密文，換電腦後密碼無法解密，需要重新填寫。",
            "Dışa aktarma bu makinede şifrelenmiş sırları içerir. Başka bir PC’de parolalar çözülemez.",
            "Экспорт содержит секреты, зашифрованные на этом ПК. На другом компьютере пароли не расшифруются.",
            "A exportação inclui segredos cifrados nesta máquina. As palavras-passe não descodificam noutro PC.",
            "Der Export enthält auf diesem Rechner verschlüsselte Geheimnisse. Passwörter sind auf einem anderen PC nicht lesbar.",
            "L’export contient des secrets chiffrés sur cette machine. Les mots de passe ne se déchiffrent pas sur un autre PC.",
            "Експорт містить секрети, зашифровані на цьому ПК. На іншому комп’ютері паролі не розшифруються.",
            "L’esportazione include segreti cifrati su questa macchina. Le password non si decifrano su un altro PC.",
            "La exportación incluye secretos cifrados en este equipo. Las contraseñas no se descifran en otro PC.",
            "내보내기에는 이 컴퓨터에서 암호화된 비밀이 들어 있습니다. 다른 PC에서는 암호를 풀 수 없습니다.",
            "Xuất gồm bí mật mã hóa trên máy này. Mật khẩu không giải được trên máy khác."),
        ["scan"] = R("Scan", "扫描", "掃描", "Tara", "Сканировать", "Analisar", "Scannen", "Analyser", "Сканувати", "Analizza", "Escanear", "스캔", "Quét"),
        ["tree"] = R("Tree", "树形", "樹狀", "Ağaç", "Дерево", "Árvore", "Baum", "Arbre", "Дерево", "Albero", "Árbol", "트리", "Cây"),
        ["flat"] = R("Flat", "平铺", "平鋪", "Liste", "Список", "Lista", "Flach", "Liste", "Список", "Elenco", "Lista", "목록", "Danh sách"),
        ["cancel"] = R("Cancel", "取消", "取消", "İptal", "Отмена", "Cancelar", "Abbrechen", "Annuler", "Скасувати", "Annulla", "Cancelar", "취소", "Hủy"),
        ["rename"] = R("Rename", "重命名", "重新命名", "Yeniden adlandır", "Переименовать", "Renomear", "Umbenennen", "Renommer", "Перейменувати", "Rinomina", "Renombrar", "이름 바꾸기", "Đổi tên"),
        ["apply_ttl"] = R("Apply TTL", "应用 TTL", "套用 TTL", "TTL uygula", "Применить TTL", "Aplicar TTL", "TTL anwenden", "Appliquer le TTL", "Застосувати TTL", "Applica TTL", "Aplicar TTL", "TTL 적용", "Áp dụng TTL"),
        ["persistent"] = R("Persistent", "持久", "持久", "Kalıcı", "Постоянный", "Persistente", "Dauerhaft", "Persistant", "Постійний", "Persistente", "Persistente", "영구", "Bền vững"),
        ["execute"] = R("Execute", "执行", "執行", "Çalıştır", "Выполнить", "Executar", "Ausführen", "Exécuter", "Виконати", "Esegui", "Ejecutar", "실행", "Thực thi"),
        ["copy_output"] = R("Copy output", "复制输出", "複製輸出", "Çıktıyı kopyala", "Копировать вывод", "Copiar saída", "Ausgabe kopieren", "Copier la sortie", "Копіювати вивід", "Copia output", "Copiar salida", "출력 복사", "Sao chép kết quả"),
        ["copy_full"] = R("Copy full", "复制全文", "複製全文", "Tümünü kopyala", "Копировать полностью", "Copiar tudo", "Alles kopieren", "Tout copier", "Копіювати повністю", "Copia tutto", "Copiar todo", "전체 복사", "Sao chép toàn bộ"),
        ["subscribe"] = R("Subscribe", "订阅", "訂閱", "Abone ol", "Подписаться", "Subscrever", "Abonnieren", "S’abonner", "Підписатися", "Iscriviti", "Suscribirse", "구독", "Đăng ký"),
        ["unsubscribe"] = R("Unsubscribe", "退订", "取消訂閱", "Abonelikten çık", "Отписаться", "Cancelar subscrição", "Abbestellen", "Se désabonner", "Відписатися", "Annulla iscrizione", "Cancelar suscripción", "구독 해제", "Hủy đăng ký"),
        ["publish"] = R("PUBLISH", "PUBLISH", "PUBLISH", "PUBLISH", "PUBLISH", "PUBLISH", "PUBLISH", "PUBLISH", "PUBLISH", "PUBLISH", "PUBLISH", "PUBLISH", "PUBLISH"),
        ["pattern"] = R("Pattern", "Pattern", "Pattern", "Desen", "Шаблон", "Padrão", "Muster", "Motif", "Шаблон", "Modello", "Patrón", "패턴", "Mẫu"),
        ["prev_page"] = R("Prev", "上一页", "上一頁", "Önceki", "Назад", "Anterior", "Zurück", "Préc.", "Назад", "Prec.", "Ant.", "이전", "Trước"),
        ["next_page"] = R("Next", "下一页", "下一頁", "Sonraki", "Далее", "Seguinte", "Weiter", "Suiv.", "Далі", "Succ.", "Sig.", "다음", "Sau"),
        ["field"] = R("Field", "Field", "Field", "Alan", "Поле", "Campo", "Feld", "Champ", "Поле", "Campo", "Campo", "필드", "Trường"),
        ["member"] = R("Member", "Member", "Member", "Üye", "Элемент", "Membro", "Element", "Membre", "Елемент", "Membro", "Miembro", "멤버", "Phần tử"),
        ["value"] = R("Value", "Value", "Value", "Değer", "Значение", "Valor", "Wert", "Valeur", "Значення", "Valore", "Valor", "값", "Giá trị"),
        ["score"] = R("Score", "Score", "Score", "Skor", "Счёт", "Score", "Score", "Score", "Оцінка", "Punteggio", "Puntuación", "점수", "Điểm"),
        ["search_in_page"] = R("Search", "搜索", "搜尋", "Ara", "Поиск", "Pesquisar", "Suchen", "Rechercher", "Пошук", "Cerca", "Buscar", "검색", "Tìm"),
        ["narrow_pattern"] = R("Too many keys, truncated. Narrow MATCH.", "结果过多，已截断。请缩小 MATCH。", "結果過多，已截斷。請縮小 MATCH。", "Çok fazla anahtar, kesildi. MATCH’i daraltın.", "Слишком много ключей, список обрезан. Сузьте MATCH.", "Demasiadas chaves, truncado. Restrinja MATCH.", "Zu viele Keys, gekürzt. MATCH eingrenzen.", "Trop de clés, tronqué. Restreignez MATCH.", "Забагато ключів, обрізано. Звузьте MATCH.", "Troppe chiavi, troncato. Restringi MATCH.", "Demasiadas claves, truncado. Acote MATCH.", "키가 너무 많아 잘렸습니다. MATCH를 좁히세요.", "Quá nhiều khóa, đã cắt. Thu hẹp MATCH."),
        ["overwrite_confirm"] = R("The value on the server has changed. Overwrite?", "服务器上的值已变化，确定覆盖？", "伺服器上的值已變化，確定覆蓋？", "Sunucudaki değer değişti. Üzerine yazılsın mı?", "Значение на сервере изменилось. Перезаписать?", "O valor no servidor mudou. Sobrescrever?", "Der Wert auf dem Server hat sich geändert. Überschreiben?", "La valeur sur le serveur a changé. Écraser ?", "Значення на сервері змінилося. Перезаписати?", "Il valore sul server è cambiato. Sovrascrivere?", "El valor en el servidor ha cambiado. ¿Sobrescribir?", "서버의 값이 변경되었습니다. 덮어쓸까요?", "Giá trị trên máy chủ đã đổi. Ghi đè?"),
        ["unsaved"] = R("Unsaved changes", "未保存的修改", "未儲存的修改", "Kaydedilmemiş değişiklikler", "Несохранённые изменения", "Alterações por guardar", "Ungespeicherte Änderungen", "Modifications non enregistrées", "Незбережені зміни", "Modifiche non salvate", "Cambios sin guardar", "저장하지 않은 변경", "Thay đổi chưa lưu"),
        ["unsaved_switch_viewer"] = R("Switching format discards unsaved changes. Continue?", "切换格式将丢弃未保存修改，确定继续？", "切換格式將丟棄未儲存修改，確定繼續？", "Biçim değiştirmek kaydedilmemiş değişiklikleri siler. Devam?", "Смена формата отменит несохранённые правки. Продолжить?", "Mudar o formato descarta alterações por guardar. Continuar?", "Formatwechsel verwirft ungespeicherte Änderungen. Fortfahren?", "Changer de format abandonne les modifications non enregistrées. Continuer ?", "Зміна формату скасує незбережені зміни. Продовжити?", "Il cambio formato scarta le modifiche non salvate. Continuare?", "Cambiar de formato descarta los cambios sin guardar. ¿Continuar?", "형식 전환 시 저장하지 않은 변경이 사라집니다. 계속할까요?", "Đổi định dạng sẽ mất thay đổi chưa lưu. Tiếp tục?"),
        ["unsaved_refresh"] = R("Refresh will discard unsaved changes. Continue?", "刷新将丢弃未保存修改，确定继续？", "重新整理將丟棄未儲存修改，確定繼續？", "Yenilemek kaydedilmemiş değişiklikleri siler. Devam?", "Обновление отменит несохранённые правки. Продолжить?", "Atualizar descarta alterações por guardar. Continuar?", "Aktualisieren verwirft ungespeicherte Änderungen. Fortfahren?", "Actualiser abandonne les modifications non enregistrées. Continuer ?", "Оновлення скасує незбережені зміни. Продовжити?", "L’aggiornamento scarta le modifiche non salvate. Continuare?", "Actualizar descarta los cambios sin guardar. ¿Continuar?", "새로고침 시 저장하지 않은 변경이 사라집니다. 계속할까요?", "Làm mới sẽ mất thay đổi chưa lưu. Tiếp tục?"),
        ["unsaved_switch_key"] = R("The current key has unsaved changes. Switch anyway?", "当前 Key 有未保存修改，确定切换？", "目前 Key 有未儲存修改，確定切換？", "Geçerli anahtarda kaydedilmemiş değişiklikler var. Yine de geçilsin mi?", "У текущего ключа есть несохранённые правки. Переключить?", "A chave atual tem alterações por guardar. Mudar mesmo assim?", "Der aktuelle Key hat ungespeicherte Änderungen. Trotzdem wechseln?", "La clé actuelle a des modifications non enregistrées. Changer quand même ?", "Поточний ключ має незбережені зміни. Все одно перемкнути?", "La chiave corrente ha modifiche non salvate. Cambiare comunque?", "La clave actual tiene cambios sin guardar. ¿Cambiar de todos modos?", "현재 키에 저장하지 않은 변경이 있습니다. 그래도 전환할까요?", "Khóa hiện tại có thay đổi chưa lưu. Vẫn chuyển?"),
        ["search_info"] = R("Search info", "搜索 Info", "搜尋 Info", "Info ara", "Поиск Info", "Pesquisar Info", "Info suchen", "Rechercher Info", "Пошук Info", "Cerca Info", "Buscar Info", "Info 검색", "Tìm Info"),
        ["ttl_updated"] = R("TTL updated", "TTL 已更新", "TTL 已更新", "TTL güncellendi", "TTL обновлён", "TTL atualizado", "TTL aktualisiert", "TTL mis à jour", "TTL оновлено", "TTL aggiornato", "TTL actualizado", "TTL이 업데이트됨", "Đã cập nhật TTL"),
        ["delete_key"] = R("Delete key", "删除 Key", "刪除 Key", "Anahtarı sil", "Удалить ключ", "Excluir chave", "Key löschen", "Supprimer la clé", "Видалити ключ", "Elimina chiave", "Eliminar clave", "키 삭제", "Xóa khóa"),
        ["group_prompt"] = R("Enter a group name. Leave empty to ungroup.", "输入分组名，留空则移出分组。", "輸入分組名，留空則移出分組。", "Grup adı girin. Boş bırakınca gruptan çıkar.", "Введите имя группы. Пустое значение убирает из группы.", "Introduza o nome do grupo. Vazio remove do grupo.", "Gruppennamen eingeben. Leer entfernt aus der Gruppe.", "Saisissez un nom de groupe. Vide retire du groupe.", "Введіть назву групи. Порожнє прибирає з групи.", "Inserisci il nome del gruppo. Vuoto toglie dal gruppo.", "Escriba un nombre de grupo. Vacío quita del grupo.", "그룹 이름을 입력하세요. 비우면 그룹에서 제거됩니다.", "Nhập tên nhóm. Để trống sẽ rời nhóm."),
        ["heartbeat_lost"] = R("Heartbeat lost", "心跳失败", "心跳失敗", "Kalp atışı kayboldu", "Пульс потерян", "Batimento perdido", "Heartbeat verloren", "Battement perdu", "Пульс втрачено", "Heartbeat perso", "Latido perdido", "하트비트 실패", "Mất heartbeat"),
        ["connected"] = R("Connected", "已连接", "已連線", "Bağlandı", "Подключено", "Ligado", "Verbunden", "Connecté", "Підключено", "Connesso", "Conectado", "연결됨", "Đã kết nối"),
        ["ready"] = R("Ready", "就绪", "就緒", "Hazır", "Готово", "Pronto", "Bereit", "Prêt", "Готово", "Pronto", "Listo", "준비됨", "Sẵn sàng"),
        ["new_version_found"] = R("New version {0} is available", "发现新版本 {0}", "發現新版本 {0}", "Yeni sürüm {0} mevcut", "Доступна новая версия {0}", "Nova versão {0} disponível", "Neue Version {0} verfügbar", "Nouvelle version {0} disponible", "Доступна нова версія {0}", "Nuova versione {0} disponibile", "Nueva versión {0} disponible", "새 버전 {0} 사용 가능", "Có phiên bản mới {0}"),
        ["slow_log_count"] = R("{0} entries", "共 {0} 条", "共 {0} 條", "{0} kayıt", "Записей: {0}", "{0} entradas", "{0} Einträge", "{0} entrées", "Записів: {0}", "{0} voci", "{0} entradas", "{0}개", "{0} mục"),
        ["memory_scan_running"] = R("Scanning with MEMORY USAGE. This may affect latency.", "正在扫描并调用 MEMORY USAGE，可能影响延迟。", "正在掃描並呼叫 MEMORY USAGE，可能影響延遲。", "MEMORY USAGE ile taranıyor, gecikmeyi etkileyebilir.", "Сканирование MEMORY USAGE, возможна задержка.", "A analisar com MEMORY USAGE. Pode afetar a latência.", "SCAN mit MEMORY USAGE, Latenz möglich.", "Analyse MEMORY USAGE, la latence peut augmenter.", "Сканування MEMORY USAGE, можлива затримка.", "Scansione MEMORY USAGE, la latenza può aumentare.", "Analizando con MEMORY USAGE. Puede afectar la latencia.", "MEMORY USAGE로 스캔 중이며 지연에 영향을 줄 수 있습니다.", "Đang quét MEMORY USAGE, có thể ảnh hưởng độ trễ."),
        ["scan_finished"] = R("Scan finished", "扫描完成", "掃描完成", "Tarama bitti", "Сканирование завершено", "Análise concluída", "Scan abgeschlossen", "Analyse terminée", "Сканування завершено", "Scansione completata", "Escaneo terminado", "스캔 완료", "Quét xong"),
        ["stopped"] = R("Stopped", "已停止", "已停止", "Durduruldu", "Остановлено", "Parado", "Gestoppt", "Arrêté", "Зупинено", "Interrotto", "Detenido", "중지됨", "Đã dừng"),
        ["memory_summary"] = R("Total: {0}    Size: {1}", "合计: {0}    Size: {1}", "合計: {0}    Size: {1}", "Toplam: {0}    Size: {1}", "Итого: {0}    Size: {1}", "Total: {0}    Size: {1}", "Gesamt: {0}    Size: {1}", "Total : {0}    Size : {1}", "Разом: {0}    Size: {1}", "Totale: {0}    Size: {1}", "Total: {0}    Size: {1}", "합계: {0}    Size: {1}", "Tổng: {0}    Size: {1}"),
    };

    public static bool TryGet(string language, string key, [NotNullWhen(true)] out string? value)
    {
        if (Table.TryGetValue(key, out var row))
        {
            var index = Array.FindIndex(Languages, item => string.Equals(item, language, StringComparison.OrdinalIgnoreCase));
            if (index >= 0 && index < row.Length && !string.IsNullOrWhiteSpace(row[index]))
            {
                value = row[index];
                return true;
            }
        }

        value = null;
        return false;
    }

    private static string[] R(params string[] texts)
    {
        if (texts.Length != Languages.Length)
        {
            throw new InvalidOperationException($"UiCatalogExtras row length {texts.Length} != {Languages.Length}.");
        }

        return texts;
    }
}
