using System.ComponentModel;

namespace RedisDesktop.App;

public sealed class UiStrings : INotifyPropertyChanged
{
    private string _language = "zh-CN";

    public event PropertyChangedEventHandler? PropertyChanged;

    public string Language => _language;

    public bool IsEnglish => _language.StartsWith("en", StringComparison.OrdinalIgnoreCase);

    public void SetLanguage(string language)
    {
        _language = string.IsNullOrWhiteSpace(language) ? "zh-CN" : language;
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(null));
    }

    public string T(string zh, string en) => IsEnglish ? en : zh;

    public string NewConnection => T("新建连接", "New Connection");
    public string Settings => T("设置", "Settings");
    public string Log => T("日志", "Log");
    public string SearchConnections => T("搜索连接", "Search connections");
    public string Connect => T("连接", "Connect");
    public string Disconnect => T("断开", "Disconnect");
    public string OpenCli => T("打开 CLI", "Open CLI");
    public string OpenPubSub => T("Pub/Sub", "Pub/Sub");
    public string CloseConnection => T("关闭连接", "Close Connection");
    public string DuplicateConnection => T("复制连接", "Duplicate Connection");
    public string MarkColor => T("标记颜色", "Mark Color");
    public string ColorRed => T("红", "Red");
    public string ColorOrange => T("橙", "Orange");
    public string ColorGreen => T("绿", "Green");
    public string ColorBlue => T("蓝", "Blue");
    public string ColorPurple => T("紫", "Purple");
    public string ColorNone => T("无", "None");
    public string More => T("更多", "More");
    public string FlushDb => T("清空当前 DB", "Flush DB");
    public string CloseToConnection => T("关闭连接会关掉该连接下所有 Tab。确定关闭？", "Closing will close all tabs for this connection. Continue?");
    public string CloseToEditConnection => T("编辑前需要先关闭连接。确定关闭并编辑？", "The connection will be closed before editing. Continue?");
    public string FlushDbPrompt => T("请输入 y 以确认清空当前数据库。", "Type y to confirm flushing the current database.");
    public string Edit => T("编辑", "Edit");
    public string Clone => T("克隆", "Clone");
    public string Delete => T("删除", "Delete");
    public string Import => T("导入连接", "Import");
    public string Export => T("导出连接", "Export");
    public string MoveToGroup => T("移动到分组", "Move to group");
    public string DarkTheme => T("暗色主题", "Dark theme");
    public string FollowSystemTheme => T("跟随系统主题", "Follow system theme");
    public string UseEnglish => T("English UI", "English UI");
    public string ScanCount => T("SCAN COUNT（默认 200）", "SCAN COUNT (default 200)");
    public string UiSettings => T("外观", "Appearance");
    public string CommonSettings => T("通用", "General");
    public string ThemeSelect => T("主题模式", "Color Theme");
    public string ThemeSystem => T("跟随系统", "System");
    public string ThemeLight => T("浅色", "Light");
    public string ThemeDark => T("深色", "Dark");
    public string SelectLang => T("语言", "Language");
    public string PageZoom => T("页面缩放", "Page Zoom");
    public string FontFamily => T("字体选择", "Font Family");
    public string FontDefault => T("默认", "Default");
    public string FontFaq => T(
        "列表来自本机已安装字体。下拉项按该字体预览，并标出能显示的文字（中文 / 日文 / 韩文等）。选定后会自动拼接系统里的多语言字体，避免缺字。选「默认」则使用界面自带字体。",
        "The list comes from fonts installed on this computer. Each item is previewed in its own typeface and shows which scripts it covers. Your pick is followed by system fallbacks so Chinese, Japanese, Korean, and other text still render. Choose Default to keep the built-in UI font.");
    public string KeysPerLoading => T("加载数量", "Load Number");
    public string KeysPerLoadingTip => T("每次 SCAN 加载的 Key 数量，设置过大可能会影响性能。", "Keys loaded per SCAN. Setting this too large may affect performance.");
    public string ConfigConnections => T("连接配置", "Connections");
    public string AppName => "Redis Desktop";
    public string PreVersion => T("当前版本", "Current Version");
    public string Hotkey => T("快捷键", "Hot Key");
    public string ClearCache => T("清除缓存", "Clear Cache");
    public string ClearCacheTip => T("当客户端出现问题时，该操作会删除所有连接和配置，用于恢复客户端。", "When the client misbehaves, this deletes all connections and settings to recover it.");
    public string ClearCacheDone => T("已清除缓存", "Cache cleared");
    public string OpenConfigFolder => T("打开配置目录", "Open Config Folder");
    public string GitHub => "GitHub";
    public string HotkeyKey => "Key";
    public string HotkeyDesc => T("说明", "Description");
    public string CommandLog => T("命令日志", "Command log");
    public string OnlyWrite => T("仅写命令", "Only Write");
    public string ClearLogs => T("清空", "Clear");
    public string EmptyWorkspace => T("从左侧连接一个 Redis 实例", "Connect a Redis instance from the sidebar");
    public string SearchKeys => T("回车搜索", "Enter To Search");
    public string ExactSearch => T("精确搜索", "Exact Search");
    public string LoadAll => T("加载所有", "Load All");
    public string LoadAllTip => T("一次性加载所有 Key，数量过多时可能导致卡顿，请酌情使用", "Load every key at once. Too many keys may freeze the client.");
    public string LoadMore => T("加载更多", "Load More");
    public string MultipleSelect => T("多项选择", "Multiple Select");
    public string OpenNewTab => T("新窗口打开", "Open In New Tab");
    public string LoadCurrentFolder => T("只加载该文件夹", "Load Current Folder");
    public string DeleteFolder => T("扫描并删除整个文件夹", "Scan And Delete Folder");
    public string ToggleCheckAll => T("全选 | 取消全选", "Select All / None");
    public string EmptyKeys => T("暂无数据", "No Data");
    public string ScanDisabled => T("SCAN 命令执行异常（可能已被禁用），无法显示 Key 列表", "SCAN is unavailable (it may be disabled). The key list cannot be shown.");
    public string TreeNodeOverflow => T("Key 或文件夹过多，仅保留 {0} 个进行展示。如未找到所需 Key，建议使用模糊搜索，或设置分隔符将 Key 分散到文件夹中", "Too many keys or folders; only {0} are shown. Narrow MATCH, or set a separator to group keys.");
    public string Copy => T("复制", "Copy");
    public string NewKey => T("新增Key", "New Key");
    public string KeyName => T("键名", "Key Name");
    public string KeyType => T("类型", "Key Type");
    public string AutoRefresh => T("自动刷新", "Auto Refresh");
    public string Server => T("服务器", "Server");
    public string Memory => T("内存", "Memory");
    public string Stats => T("统计", "Stats");
    public string KeyStatistics => T("Key 统计", "Key Statistics");
    public string AllRedisInfo => T("全部 Redis Info", "All Redis Info");
    public string Home => T("首页", "Home");
    public string Version => T("版本", "Version");
    public string RedisVersionLabel => T("Redis 版本", "Redis Version");
    public string OsLabel => "OS";
    public string Process => T("进程", "Process ID");
    public string UsedMemory => T("已用内存", "Used Memory");
    public string UsedMemoryPeak => T("内存峰值", "Used Memory Peak");
    public string UsedMemoryLua => T("Lua 内存", "Used Memory Lua");
    public string Clients => T("客户端", "Connected Clients");
    public string TotalConnections => T("总连接数", "Total Connections");
    public string TotalCommands => T("总命令数", "Total Commands");
    public string EmptyConnections => T("还没有连接。点上方「新建连接」开始。", "No connections yet. Click New Connection above.");
    public string PickKey => T("在左侧选择一个 Key", "Select a key on the left");
    public string DatabaseAlias => T("DB 别名（可空）", "DB alias (optional)");
    public string GroupName => T("分组名（可空）", "Group name (optional)");
    public string Group => T("分组", "Group");
    public string SelectGroup => T("选择分组", "Select group");
    public string Host => T("Host", "Host");
    public string Port => T("端口", "Port");
    public string Password => T("密码", "Password");
    public string Username => T("用户名", "Username");
    public string ConnectionName => T("连接名", "Connection Name");
    public string Separator => T("分隔符", "Separator");
    public string SeparatorTip => T("用于把 Key 显示成树。留空则只用平铺列表。", "Used to display keys as a tree. Leave empty to disable tree view.");
    public string SeparatorPlaceholder => T("留空则关闭树形视图", "Empty To Disable Tree View");
    public string AclUsernameHint => T("Redis 6.0+ ACL", "ACL in Redis >= 6.0");
    public string PrivateKey => T("私钥", "Private Key");
    public string PublicKey => T("公钥", "Public Key");
    public string Authority => T("CA 证书", "Authority");
    public string RedisNodePassword => T("Redis 节点密码", "Redis Node Password");
    public string MasterGroupName => T("Master 组名", "Master Group Name");
    public string SkipCertValidation => T("跳过证书校验（不安全）", "Skip certificate validation (insecure)");
    public string ClusterHint => T("Cluster 的 Host 请填节点通告地址，不要填只在本机有效的 127.0.0.1。", "Use the advertised cluster node address, not a localhost-only 127.0.0.1.");
    public string SentinelHint => T("Host/Port 填 Sentinel 节点。上方密码为 Sentinel AUTH，节点密码在 Sentinel 区域填写。", "Host/Port are Sentinel nodes. The password above is Sentinel AUTH; the Redis node password is in the Sentinel section.");
    public string ReadonlyHint => T("只读连接会拦截写命令。", "Read-only connections reject write commands.");
    public string EditConnection => T("编辑连接", "Edit Connection");
    public string Ok => T("确定", "OK");
    public string ColorTag => T("颜色标记", "Color tag");
    public string ShowPassword => T("显示密码", "Show passwords");
    public string TestConnection => T("测试连接", "Test connection");
    public string Shortcuts => T("Ctrl+N 新建连接 · Ctrl+, 设置 · Ctrl+G 命令日志", "Ctrl+N New connection · Ctrl+, Settings · Ctrl+G Command log");
    public string HotkeyCloseTab => T("关闭 Tab", "Close Tab");
    public string HotkeyRefreshTab => T("刷新 [Status / Key]", "Refresh [Status / Key]");
    public string HotkeyDeleteKey => T("删除 Key [Key Tab]", "Delete key [Key Tab]");
    public string HotkeySaveKey => T("保存 [Key Tab]", "Save [Key Tab]");
    public string HotkeyClearCli => T("清屏 [CLI Tab]", "Clear [CLI Tab]");
    public string HotkeyOpenNewTab => T("在新 Tab 打开 Key", "Open key in a new tab");
    public string HotkeyTips => T("快捷键说明", "Hotkey tips");
    public string ExportWarning => T(
        "导出会包含本机加密后的密码密文，换电脑后密码无法解密，需要重新填写。",
        "Export includes machine-encrypted secrets. Passwords will not decrypt on another PC.");
    public string Scan => T("扫描", "Scan");
    public string Tree => T("树形", "Tree");
    public string Flat => T("平铺", "Flat");
    public string Cancel => T("取消", "Cancel");
    public string Refresh => T("刷新", "Refresh");
    public string Save => T("保存", "Save");
    public string Rename => T("重命名", "Rename");
    public string ApplyTtl => T("应用 TTL", "Apply TTL");
    public string Persistent => T("持久", "Persistent");
    public string Status => T("状态", "Status");
    public string Execute => T("执行", "Execute");
    public string CopyOutput => T("复制输出", "Copy output");
    public string CopyFull => T("复制全文", "Copy full");
    public string Subscribe => T("订阅", "Subscribe");
    public string Unsubscribe => T("退订", "Unsubscribe");
    public string Publish => T("PUBLISH", "PUBLISH");
    public string Pattern => T("Pattern", "Pattern");
    public string PrevPage => T("上一页", "Prev");
    public string NextPage => T("下一页", "Next");
    public string Add => T("新增", "Add");
    public string AddNewLine => T("新增行", "Add New Line");
    public string EditLine => T("编辑行", "Edit Line");
    public string Field => T("Field", "Field");
    public string Member => T("Member", "Member");
    public string Value => T("Value", "Value");
    public string Score => T("Score", "Score");
    public string SearchInPage => T("搜索", "Search");
    public string DumpRow => T("导出命令", "Dump Command");
    public string NarrowPattern => T("结果过多，已截断。请缩小 MATCH。", "Too many keys, truncated. Narrow MATCH.");
    public string OverwriteConfirm => T("服务器上的值已变化，确定覆盖？", "The value on the server has changed. Overwrite?");
    public string Unsaved => T("未保存的修改", "Unsaved changes");
    public string UnsavedSwitchViewer => T("切换格式将丢弃未保存修改，确定继续？", "Switching format discards unsaved changes. Continue?");
    public string UnsavedRefresh => T("刷新将丢弃未保存修改，确定继续？", "Refresh will discard unsaved changes. Continue?");
    public string UnsavedSwitchKey => T("当前 Key 有未保存修改，确定切换？", "The current key has unsaved changes. Switch anyway?");
    public string TtlDeleteConfirm => T("TTL 为 0 会删除该 Key，确定继续？", "TTL 0 will delete this key. Continue?");
    public string Persist => T("持久化（-1）", "Persist (-1)");
    public string DumpCommand => T("导出命令到剪贴板", "Dump command to clipboard");
    public string AutoRefreshTip => T("自动刷新（2 秒）", "Auto refresh (2s)");
    public string SearchInfo => T("搜索 Info", "Search info");
    public string InfoDisabled => T("INFO 命令不可用（可能已被禁用）", "INFO command is unavailable (it may be disabled).");
    public string Node => "Node";
    public string RenameHint => T("修改后按 Enter 重命名", "Press Enter to rename");
    public string TtlHint => T("TTL 秒，-1 为持久", "TTL seconds, -1 = persist");
    public string Copied => T("已复制", "Copied");
    public string Saved => T("已保存", "Saved");
    public string Deleted => T("已删除", "Deleted");
    public string TtlUpdated => T("TTL 已更新", "TTL updated");
    public string HexTag => "[Hex]";
    public string DeleteKey => T("删除 Key", "Delete key");
    public string DeleteConnection => T("删除连接", "Delete connection");
    public string GroupPrompt => T("输入分组名，留空则移出分组。", "Enter a group name. Leave empty to ungroup.");
    public string HeartbeatLost => T("心跳失败", "Heartbeat lost");
    public string Connected => T("已连接", "Connected");
    public string Ready => T("就绪", "Ready");
}
